### ISSUE TITLE
Bug: Sats as currency generates invoice with 0

### ISSUE THREAD

**Issue by AxelHamburch** [lnbits/lnurldevice#13]
An instance with currency "sats" generates (for the switch) a LNURL string which contains decoded Min / Max = 0. No matter what amount you specify. Many wallets do not handle this and even if you adjust the amount correctly, an error message is displayed.

**Comment by pieterjm** [comment]
The bug is located here:

https://github.com/lnbits/lnurldevice/blob/1669a1d8b3ae6d86367408689c8d8ceda355fd71/lnurl.py#L112-L119

amount_in_cent is set to 0, and when currency == 'sat', then amount_in_cent is used to set price_msat. 

The value of 'amount' should be taken instead of 'amount_in_cent' on Line 118. 

As amount is a String, an additional conversion to int is recommended.

**Comment by pieterjm** [comment]
Created a fix for the bug

https://github.com/lnbits/lnurldevice/compare/main...pieterjm:lnurldevice:switch_sats_bug

**Comment by pieterjm** [comment]
Created pull request #14
